version: "3.8"

services:
  keycloak-postgres-sandbox:
    container_name: keycloak-postgres-sandbox
    image: library/postgres
    volumes:
      - ./keycloak-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: keycloak_db
    ports:
      - "5432:5432"
    restart: unless-stopped

  keycloak-sandbox:
    container_name: keycloak-sandbox
    image: jboss/keycloak
    environment:
      - "DB_VENDOR=POSTGRES"
      - "DB_ADDR=keycloak-postgres-sandbox"
      - "DB_DATABASE=keycloak_db"
      - "DB_USER=${POSTGRES_USER:-postgres}"
      - "DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}"
      - "KEYCLOAK_USER=admin"
      - "KEYCLOAK_PASSWORD=admin_password"
    ports:
      - "8484:8080"
    depends_on:
      - keycloak-postgres-sandbox
    links:
      - "keycloak-postgres-sandbox:keycloak-postgres-sandbox"

  vault-sandbox:
    container_name: vault-sandbox
    image: vault
    volumes:
      - ./config.hcl:/vault/config/config.hcl
      - ./vault-data:/mnt
    entrypoint: vault server -config=vault/config/config.hcl
    ports:
      - "8200:8200"
    environment:
      - "VAULT_ADDR=http://127.0.0.1:8200"

  rabbitmq-sandbox:
    container_name: rabbitmq-sandbox
    image: "rabbitmq:3.6-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
  
  config-server-sandbox:
    container_name: config-server-sandbox
    image: vlebediantsev/config-server
    ports:
      - "7777:7777"

  file-system-ms-postgres-sandbox:
    container_name: file-system-ms-postgres-sandbox
    image: library/postgres
    volumes:
      - ./ms-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: file_system_user
      POSTGRES_PASSWORD: 1q2w3e
      POSTGRES_DB: file_system
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin4-sandbox:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: sandbox@test.com
      PGADMIN_DEFAULT_PASSWORD: 1q2w3e
    ports:
      - "8889:80"

  file-system-ms-sandbox:
    container_name: file-system-ms-sandbox
    image: vlebediantsev/file-system
    ports:
      - "8080:8080"
    environment:
      ROOT: bin/root
      ARCHIVE-ROOT: bin/archive-root
      RABBIT_MQ_HOST: rabbitmq-sandbox
      RABBIT_MQ_USERNAME: guest
      RABBIT_MQ_PORT: 5672
      RABBIT_MQ_DESTINATION: filesystem.notifications.exchange
      DB_URL: file-system-ms-postgres-sandbox
      DB_PORT: 5432
      DB_NAME: file_system
      DB_USERNAME: file_system_user
      KEYCLOAK_URL: keycloak-sandbox
      KEYCLOAK_PORT: 8080
      CONFIG_SERVER_URL: config-server-sandbox
      CONFIG_SERVER_PORT: 7777
      VAULT_HOST: vault-sandbox
      VAULT_PORT: 8200
      VAULT_URL: http://vault-sandbox:8200
    depends_on:
      vault-sandbox:
        condition: service_started
      config-server-sandbox:
        condition: service_started
      keycloak-sandbox:
        condition: service_started
      rabbitmq-sandbox:
        condition: service_started
      file-system-ms-postgres-sandbox:
        condition: service_healthy
    links:
      - file-system-ms-postgres-sandbox
